FROM ubuntu:jammy AS base
RUN apt update && apt install -y curl unzip && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://bun.sh/install | bash && cp ~/.bun/bin/bun /usr/bin/bun
WORKDIR /app

FROM base AS release

COPY package.json .
COPY bun.lockb .

RUN bun install --production
COPY src src
COPY tsconfig.json .

ENV NODE_ENV production
VOLUME ["/app/public/books"]
CMD ["bun", "src/index.ts"]

EXPOSE 3000